theme: jekyll-theme-cayman
title: gemstone.gemtem
description: GPA Gemstone GemTem Library
github:
  repository_name: gemstone.gemtem
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji