theme: jekyll-theme-cayman
title: Gemstone.PQDIF
description: GPA Gemstone PQDIF Library
github:
  repository_name: gemstone/pqdif
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
